### ISSUE TITLE
Missing required attribute `authors`

### ISSUE THREAD

**Issue by kantharia** [jonz94/capacitor-sim#1]
I am facing issue when I try to execute `ionic cap sync ios`. I m getting following error

<img width="918" alt="Screenshot 2023-02-22 at 9 49 35 AM" src="https://user-images.githubusercontent.com/8065874/220520935-a4020e9a-f19b-429d-8e08-23c2199fe010.png">

**Comment by jonz94** [comment]
Hi @kantharia,

Thank you for reporting the issue, and I can reproduce the error on my end.
I'm not sure why I didn't get this error when I testing it few months ago 🤔

Anyway, I just publish a new version.
Upgrade the plugin to `@jonz94/capacitor-sim@1.0.3` should be able to fix this issue.
